export const tracks=['bgm_01_cafe_open.mp3','bgm_02_measure_and_mix.mp3','bgm_03_cafe_rush.mp3','bgm_04_perfect_service.mp3'];
export type Sfx='uiTap'|'uiBack'|'ingredientSelect'|'pour'|'fractionSnap'|'combine'|'correct'|'wrong'|'serve'|'customerHappy'|'combo'|'dayClear';
const read=(key:string,fallback:number)=>{try{const v=localStorage.getItem('fractionCafe_'+key);return v===null?fallback:Number(v)}catch{return fallback}};
export class AudioManager {
  bgmEnabled=!!read('bgmEnabled',1);sfxEnabled=!!read('sfxEnabled',1);bgmVolume=read('bgmVolume',.22);sfxVolume=read('sfxVolume',.55);
  private channels:HTMLAudioElement[]=[];private active=0;private desired=0;private current=-1;private unlocked=false;private ducked=false;private frame=0;private context:AudioContext|null=null;
  unlock(){if(this.unlocked)return;this.unlocked=true;this.channels=[new Audio(),new Audio()];this.channels.forEach(a=>{a.loop=true;a.preload='auto'});this.setTrack(this.desired);}
  setTrack(index:number){this.desired=index;if(!this.unlocked||this.current===index)return;cancelAnimationFrame(this.frame);const old=this.channels[this.active];this.active=1-this.active;const next=this.channels[this.active];next.src='./audio/'+tracks[index];next.volume=0;next.load();this.current=index;if(this.bgmEnabled)void next.play().catch(()=>{});const start=performance.now(),oldVolume=old.volume;const fade=()=>{const p=Math.min(1,(performance.now()-start)/650);next.volume=p*this.level();old.volume=oldVolume*(1-p);if(p<1)this.frame=requestAnimationFrame(fade);else old.pause()};this.frame=requestAnimationFrame(fade);}
  private level(){return this.bgmEnabled?this.bgmVolume*(this.ducked?.38:1):0}
  duck(value:boolean){this.ducked=value;if(this.channels.length)this.channels[this.active].volume=this.level()}
  set(kind:'bgm'|'sfx',enabled:boolean){this[kind+'Enabled' as 'bgmEnabled'|'sfxEnabled']=enabled;try{localStorage.setItem('fractionCafe_'+kind+'Enabled',String(Number(enabled)));localStorage.setItem('fractionCafe_bgmVolume',String(this.bgmVolume));localStorage.setItem('fractionCafe_sfxVolume',String(this.sfxVolume))}catch{}if(kind==='bgm'&&this.channels.length){const a=this.channels[this.active];a.volume=this.level();if(enabled)void a.play().catch(()=>{});else a.pause()}}
  playSfx(name:Sfx){if(!this.sfxEnabled)return;try{this.context??=new AudioContext();const c=this.context;void c.resume();const notes:Record<Sfx,number[]>={uiTap:[360],uiBack:[270],ingredientSelect:[530],pour:[260],fractionSnap:[660,990],combine:[430,645],correct:[660,880],wrong:[220,196],serve:[780,1040],customerHappy:[880],combo:[660,880,1100],dayClear:[523,659,784,1046]};notes[name].forEach((hz,i)=>{const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*.085;o.type=name==='pour'?'triangle':'sine';o.frequency.setValueAtTime(hz,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.12*this.sfxVolume,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.connect(g).connect(c.destination);o.start(t);o.stop(t+.17)})}catch{}}
}
export const audio=new AudioManager();
