(()=>{
 'use strict';
 const {questions,typeNames,grade}=window.CafeQuiz,config=window.CAFE_QUIZ_CONFIG,app=document.getElementById('app');
 let index=0,answers=[],draft=null,locked=false,countdown=null,transitioning=false;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const frac=(w,n,d)=>`<span class="mixed" aria-label="${w?w+'과 ':''}${d}분의 ${n==='?'?'빈칸':n}">${w?`<b>${w}</b>`:''}<span class="fraction"><span>${n==='?'?'□':n}</span><span>${d}</span></span></span>`;
 function rich(text){return esc(text).replace(/\{(?:(\d+) )?(\d+|\?)\/(\d+)\}/g,(_,w,n,d)=>frac(w,n,d))}
 const button=(label,action,css='primary')=>`<button class="${css}" data-action="${action}">${label}</button>`;
 function scene(q){let v=q.visual,diagram='';if(v){const bar=(n,label)=>`<div class="fraction-model"><span>${label}</span><div class="parts" style="--parts:${v.d}">${Array.from({length:v.d},(_,i)=>`<i class="${i<n?'filled':''}"></i>`).join('')}</div></div>`;diagram=v.kind==='pair'?bar(v.a,'탄산수')+bar(v.b,'레몬 베이스'):bar(v.kind==='divisions'?0:v.a,v.kind==='divisions'?'같은 크기의 8부분':'처음에 있던 양')}
 return `<aside class="scene"><span class="scene-label">오늘의 카페 미션</span><img src="image/${q.image}" alt="${esc(q.scene)}"><h2>${esc(q.scene)}</h2>${diagram}<small>그림 속 장식이 아닌<br>주문에 적힌 양을 살펴봐요.</small></aside>`}
 function focusHeading(){app.querySelector('h1')?.focus()}
 function home(){clearInterval(countdown);answers=[];index=0;draft=null;locked=false;transitioning=false;app.innerHTML=`<section class="welcome"><div class="welcome-copy"><span class="eyebrow">FRACTION CAFÉ · ENTRY QUIZ</span><h1 tabindex="-1">분수 실력을 모아<br><em>카페 문을 열어요!</em></h1><p>주문을 읽고, 분수를 계산하고,<br>카페 입장 도장 7개를 모아 보세요.</p><div class="rules"><span><b>10</b> 문제</span><span><b>7</b> 개 이상 정답</span><span><b>시간 제한 없음</b></span></div>${button('입장 퀴즈 시작하기 →','start')}<p class="fine">문항마다 정답과 해설을 확인해요.<br>10문제를 모두 풀고 통과하면 분수카페로 자동 이동합니다.</p></div><div class="welcome-art"><div class="halo"></div><img src="image/host.png" alt="카페 입장을 안내하는 직원"><div class="welcome-ticket"><b>CAFE PASS</b><span>분수를 알면, 입장 준비 완료!</span></div></div></section>`;focusHeading()}
 function progress(){return `<div class="quiz-status"><b>문제 ${index+1} <span>/ 10</span></b><div class="stamps" aria-label="현재 정답 ${answers.filter(x=>x.correct).length}개">${questions.map((_,i)=>`<span class="${answers[i]?(answers[i].correct?'yes':'no'):i===index?'now':''}" aria-label="${i+1}번 ${answers[i]?(answers[i].correct?'정답':'오답'):'미완료'}">${answers[i]?(answers[i].correct?'✓':'·'):i+1}</span>`).join('')}</div><small>정답 도장 <strong>${answers.filter(x=>x.correct).length}</strong> / 7</small></div>`}
 function options(q){if(q.type==='short'||q.type==='initial')return `<div class="text-response">${q.hint?`<span class="initial-hint">${q.hint}</span>`:''}<label for="response">${q.type==='short'?'□에 들어갈 자연수':'초성에 맞는 두 글자'}</label><input id="response" type="text" ${q.type==='short'?'inputmode="numeric"':''} maxlength="20" autocomplete="off" spellcheck="false" placeholder="${q.type==='short'?'숫자만 써요':'낱말을 써요'}" aria-describedby="input-note"><small id="input-note">${q.type==='short'?'분수 전체가 아니라 빈칸의 숫자만 입력하세요.':'초성을 그대로 쓰지 말고 완성된 낱말을 입력하세요.'}</small></div>`;
 if(q.type==='sequence')return `<div class="sequence-answer" aria-live="polite">선택한 순서: <b id="sequence-order">아직 고르지 않았어요</b></div><div class="sequence-cards">${q.options.map((t,i)=>`<button class="option sequence-card" data-option="${i}" aria-pressed="false"><span class="letter">${String.fromCharCode(65+i)}</span>${rich(t)}</button>`).join('')}</div><button class="quiet" data-action="undo">마지막 선택 취소</button>`;
 return `<div class="options ${q.type==='ox'?'ox':''}">${q.options.map((t,i)=>`<button class="option" data-option="${i}" aria-pressed="false">${q.type==='ox'?'':`<span class="letter">${i+1}</span>`}${rich(t)}</button>`).join('')}</div>`}
 function question(){locked=false;draft=questions[index].type==='sequence'?[]:null;const q=questions[index];app.innerHTML=progress()+`<div class="question-layout">${scene(q)}<section class="question-card"><span class="type-tag">${typeNames[q.type]}</span><h1 tabindex="-1">${q.id}. ${q.title}</h1><p class="prompt">${rich(q.prompt)}</p>${q.equation?`<div class="equation">${rich(q.equation)}</div>`:''}<div id="answer-controls">${options(q)}</div><p id="notice" class="notice" role="status"></p><div id="feedback"></div><div class="question-actions">${button('정답 확인','check')}<small>한 문제는 한 번만 채점해요.</small></div></section></div>`;focusHeading()}
 function choose(n){if(locked)return;const q=questions[index];if(q.type==='sequence'){if(draft.includes(n))return;draft.push(n)}else draft=n;updateOptions()}
 function updateOptions(){const q=questions[index];app.querySelectorAll('[data-option]').forEach(b=>{const n=Number(b.dataset.option),chosen=q.type==='sequence'?draft.includes(n):draft===n;b.classList.toggle('selected',chosen);b.setAttribute('aria-pressed',String(chosen));if(q.type==='sequence'){b.disabled=chosen;b.querySelector('.letter').textContent=chosen?(draft.indexOf(n)+1)+'번째':String.fromCharCode(65+n)}});if(q.type==='sequence')document.getElementById('sequence-order').textContent=draft.length?draft.map(i=>String.fromCharCode(65+i)).join(' → '):'아직 고르지 않았어요';document.getElementById('notice').textContent=''}
 function submit(){if(locked)return;const q=questions[index],input=document.getElementById('response');if(input)draft=input.value;const valid=q.type==='sequence'?draft.length===q.options.length:q.type==='short'||q.type==='initial'?String(draft??'').trim().length>0:draft!==null;if(!valid){document.getElementById('notice').textContent=q.type==='sequence'?'계산 카드를 모두 골라 순서를 완성해 주세요.':'답을 먼저 골라 주거나 입력해 주세요.';input?.focus();return}locked=true;const correct=grade(q,draft);answers.push({value:Array.isArray(draft)?[...draft]:draft,correct});app.querySelectorAll('#answer-controls button,#answer-controls input').forEach(e=>e.disabled=true);document.getElementById('notice').textContent='';document.getElementById('feedback').innerHTML=`<div class="feedback ${correct?'correct':'incorrect'}" role="status"><h2>${correct?'✓ 정답! 입장 도장을 모았어요.':'다음 문제에 다시 도전해 봐요.'}</h2><b>정답: ${rich(answerRich(q))}</b><p>${rich(q.explanation)}</p></div>`;app.querySelector('.question-actions').innerHTML=button(index===9?'10문제 결과 확인 →':'해설 확인! 다음 문제 →','next');app.querySelector('.question-actions button').focus();app.querySelector('.quiz-status').outerHTML=progress()}
 function answerRich(q){return q.type==='choice'?q.options[q.answer]:q.answerText}
 function resolveGame(){const url=new URL(config.gameUrl,location.href);if(!['file:','http:','https:'].includes(url.protocol))throw Error('지원하지 않는 게임 주소입니다.');return url.href}
 function enter(){if(answers.length!==10||answers.filter(a=>a.correct).length<config.passScore||transitioning)return;try{const url=resolveGame();transitioning=true;clearInterval(countdown);location.assign(url)}catch(e){transitioning=false;document.getElementById('move-note').textContent='게임 주소를 확인해 주세요. config.js의 gameUrl을 수정할 수 있습니다.'}}
 function results(){const score=answers.filter(x=>x.correct).length,pass=score>=config.passScore;let seconds=config.autoEnterSeconds;app.innerHTML=`<section class="results"><span class="eyebrow">${pass?'CAFE PASS · UNLOCKED':'ONE MORE TRY'}</span><h1 tabindex="-1">${pass?'입장 준비 완료!':'조금만 더 연습해 볼까요?'}</h1><div class="score-circle"><strong>${score}</strong><span> / 10문제</span></div><p>${pass?'분수카페에서 오늘의 영업을 시작해 보세요!':'7문제 이상 맞히면 입장할 수 있어요.<br>해설을 살펴보고 다시 도전해 보세요.'}</p>${pass?`${button('지금 분수카페 입장하기 →','enter')}<p id="move-note" role="status">${seconds}초 뒤 분수카페로 이동합니다.</p>${button('해설 더 보기 · 자동 이동 멈추기','pause','quiet')}`:button('10문제 다시 도전하기','retry')}<details id="review"><summary>10문제 정답과 해설 모아 보기</summary>${questions.map((q,i)=>`<article class="review-item"><span>${answers[i].correct?'✓ 정답':'다시 보기'}</span><h2>${q.id}. ${q.title}</h2><p>${rich(q.prompt)}</p>${q.equation?`<p>${rich(q.equation)}</p>`:''}<b>정답: ${rich(answerRich(q))}</b><p>${rich(q.explanation)}</p></article>`).join('')}</details></section>`;focusHeading();if(pass){countdown=setInterval(()=>{seconds--;const n=document.getElementById('move-note');if(n)n.textContent=`${Math.max(0,seconds)}초 뒤 분수카페로 이동합니다.`;if(seconds<=0)enter()},1000)}}
 app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.option!==undefined){choose(Number(b.dataset.option));return}switch(b.dataset.action){case'start':question();break;case'check':submit();break;case'next':if(!locked)return;if(index<9){index++;question()}else results();break;case'undo':if(!locked&&Array.isArray(draft)){draft.pop();updateOptions()}break;case'retry':home();question();break;case'enter':enter();break;case'pause':clearInterval(countdown);document.getElementById('move-note').textContent='자동 이동을 멈췄어요. 준비되면 입장 버튼을 눌러 주세요.';document.getElementById('review').open=true;break}});
 app.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing&&e.target.id==='response'){e.preventDefault();submit()}});
 home();
})();
