import {useEffect,useMemo,useRef,useState} from 'react';
import {Fraction} from './Fraction';
import {FractionCup} from '../CafeApp';
import {seededRandom} from '../game/generator';
import {GAME_CONFIG} from '../game/config';
import {ingredients} from '../data/gameData';
import {asset} from '../assets';
import {audio} from '../services/audio';
import {event} from '../services/analytics';

export function useDialogFocus(active:boolean,selector:string,onClose:()=>void){const close=useRef(onClose);close.current=onClose;useEffect(()=>{if(!active)return;const panel=document.querySelector<HTMLElement>(selector),previous=document.activeElement as HTMLElement|null;if(!panel)return;const buttons=()=>[...panel.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')];buttons()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close.current()}if(e.key==='Tab'){const all=buttons(),first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};panel.addEventListener('keydown',key);return()=>{panel.removeEventListener('keydown',key);previous?.focus()}},[active,selector])}

export function HelpConceptExamples(){return <div className="concept-examples"><article className="ref-cup-help"><h3>분수는 무엇을 1로 볼까요?</h3><div><FractionCup units={1} denominator={4} color="#f3ce60" hideBadge/></div><p>분수카페에서는 완성 음료컵 1컵을 1로 정해요. 우유 1/4컵과 초코 베이스 1/4컵은 같은 기준컵의 1/4만큼이에요. 재료병이나 우유팩의 크기가 달라도, 계산할 때는 모두 이 기준컵으로 옮겨서 양을 재요.</p></article><article><h3>분모가 5라면?</h3><div><FractionCup units={0} denominator={5} color="#f0ca50" blank hideBadge/><b>→ 5 →</b><FractionCup units={0} denominator={5} color="#f0ca50" hideBadge/></div><p>분모만큼 똑같이 나눠요!</p></article><article><h3>완성량 라벨 붙이기</h3><div><Fraction numerator={3} denominator={8}/><b>+</b><Fraction numerator={2} denominator={8}/><b>→</b><Fraction numerator="?" denominator={8}/><b>→</b><Fraction numerator={5} denominator={8}/></div><p>채워진 칸을 확인하고 라벨을 붙여요!</p></article></div>}

export function denominatorChoices(d:number,seed:number){const rng=seededRandom(seed),pool=[3,4,5,6,8,10,12].filter(n=>n!==d);const out=[d];while(out.length<GAME_CONFIG.denominatorChoiceCount&&pool.length)out.push(pool.splice(Math.floor(rng()*pool.length),1)[0]);return out.sort((a,b)=>a-b)}
export function DenominatorSetup({d,seed,disabled,onAttempt,retry=false}:{d:number;seed:number;disabled:boolean;retry?:boolean;onAttempt:(n:number)=>void}){return <div className={`equipment-setup ${retry?'concept-retry':''}`}><FractionCup units={0} denominator={d} color="#f3ce60" blank hideBadge/><div><h3>눈금 설정</h3><p>컵을 몇 등분할까요?</p><div className="division-choices">{denominatorChoices(d,seed).map(n=><button className="blue" key={n} disabled={disabled} onClick={()=>onAttempt(n)} aria-label={`${n}등분`}>{n}</button>)}</div><small>주문서의 분모를 살펴봐요.</small></div></div>}

export function ResultLabel({d,total,mixed,addition,color,disabled,onAttempt,carryParts=0}:{d:number;total:number;mixed:boolean;addition:boolean;color:string;disabled:boolean;carryParts?:number;onAttempt:(correct:boolean,attempt:number)=>void}){
 const [whole,setWhole]=useState(0),[numerator,setNumerator]=useState<number|null>(null),[attempt,setAttempt]=useState(0),[hint,setHint]=useState('');
 const submit=()=>{if(disabled)return;const count=attempt+1;setAttempt(count);const correct=numerator!==null&&whole*d+numerator===total;if(!correct)setHint(count>=2?'몇 칸이 채워졌는지 세어 볼까요?':'눈금과 계산을 한 번 더 확인해 봐요!');onAttempt(correct,count)};
 return <div className={`label-workshop ${attempt>=2?'highlight-fill':''}`}><div className="result-clue"><span>{addition?'합친 컵':'남은 재고'}</span>{carryParts>=d&&<div className="carry-pieces" aria-label="가득 찬 분수 조각을 온전한 컵으로"><div style={{gridTemplateColumns:`repeat(${d},1fr)`}}>{Array.from({length:carryParts},(_,i)=><i key={i} style={{background:color}}/>)}</div><small>가득 찬 칸 → 온전한 1</small></div>}<FractionCup units={total} denominator={d} color={color} hideBadge/></div><div className="label-editor"><h3>컵 라벨 붙이기</h3><small>{addition?'완성량은 얼마일까요?':'남은 양은 얼마일까요?'}</small><div className="editable-label" aria-label="아직 확인하지 않은 양">{mixed&&<b>{whole}</b>}<Fraction numerator={numerator??'?'} denominator={d} unit="컵"/></div><div className="label-steppers">{mixed&&<div><small>온전한 수</small><div><button aria-label="온전한 수 줄이기" disabled={disabled||whole===0} onClick={()=>setWhole(n=>n-1)}>−</button><b>{whole}</b><button aria-label="온전한 수 늘리기" disabled={disabled||whole>=6} onClick={()=>setWhole(n=>n+1)}>+</button></div></div>}<div><small>분자</small><div><button aria-label="분자 줄이기" disabled={disabled||numerator===0} onClick={()=>setNumerator(n=>Math.max(0,(n??1)-1))}>−</button><b>{numerator??'?'}</b><button aria-label="분자 늘리기" disabled={disabled||numerator===d-1} onClick={()=>setNumerator(n=>Math.min(d-1,(n??0)+1))}>+</button></div></div></div><button className="orange" disabled={disabled} onClick={submit}>{addition?'완성량 확인':'남은 양 확인'}</button><p className="concept-hint" role="status">{hint||'완성량 라벨을 붙여 주세요!'}</p></div></div>;
}

export type CombineChallenge={type:'combine';index:number;d:number;a:number;b:number;target:number;choicesA:number[];choicesB:number[]};
export type UseChallenge={type:'use';index:number;d:number;stock:number;target:number;use:number;options:number[]};
export function specialChallenge(seed:number,dayId=1):CombineChallenge|UseChallenge{
 const rng=seededRandom(seed^0x5531),d=[5,6,8][Math.floor(rng()*3)],index=2+Math.floor(rng()*3);
 if(dayId<=2){const a=1+Math.floor(rng()*(d-2)),b=1+Math.floor(rng()*(d-a-1));return {type:'combine',index,d,a,b,target:a+b,choicesA:[...new Set([a,Math.max(1,a-1),a+1])].sort((x,y)=>x-y),choicesB:[...new Set([b,Math.max(1,b-1),b+1])].sort((x,y)=>x-y)}}
 if(dayId<=4){const stock=2+Math.floor(rng()*(d-2)),target=1+Math.floor(rng()*(stock-1)),use=stock-target;return {type:'use',index,d,stock,target,use,options:[...new Set([use,Math.max(1,use-1),Math.min(stock-1,use+1)])].sort((x,y)=>x-y)}}
 const stock=d,target=1+Math.floor(rng()*(d-1)),use=d-target;return {type:'use',index,d,stock,target,use,options:[...new Set([use,Math.max(1,use-1),Math.min(d-1,use+1)])].sort((x,y)=>x-y)};
}
export function SpecialOrder({seed,day,disabled,onDone}:{seed:number;day:number;disabled:boolean;onDone:()=>void}){
 const challenge=useMemo(()=>specialChallenge(seed,day),[seed,day]),[a,setA]=useState<number|null>(null),[b,setB]=useState<number|null>(null),[choice,setChoice]=useState<number|null>(null),[message,setMessage]=useState(challenge.type==='combine'?'재료 카드를 한 장씩 골라 목표량을 만들어요.':day<=4?'현재 재고와 목표 재고를 보고 사용할 양을 골라요.':'온전한 1컵을 열어 재고를 딱 맞춰 봐요.'),[solved,setSolved]=useState(false);
 const title=challenge.type==='combine'?'✦ 특별 주문! 목표량을 만들어 주세요!':day<=4?'✦ 특별 주문! 이만큼 남겨 주세요!':'✦ 긴급 주문! 재고를 딱 맞춰요!';
 const submit=()=>{if(solved){onDone();return}
  const correct=challenge.type==='combine'?(a??0)+(b??0)===challenge.target:choice===challenge.use;
  event('special_order_complete',{day,correct});audio.playSfx(correct?'correct':'wrong');
  if(correct){setSolved(true);setMessage('딱 맞춰! 특별 주문 보너스 +25점')}else setMessage(challenge.type==='combine'?'두 재료를 합친 양을 다시 살펴봐요.':'남은 양을 다시 계산해 봐요.')};
 return <div className="special-shade"><section className="special-panel" aria-label="특별 주문"><h2>{title}</h2>
 {challenge.type==='combine'?<><div className="special-target"><FractionCup units={challenge.target} denominator={challenge.d} color="#edc454" hideBadge/><p>목표 완성량 <Fraction numerator={challenge.target} denominator={challenge.d} unit="컵"/></p></div><div className="special-ingredients">{[challenge.choicesA,challenge.choicesB].map((choices,i)=><div key={i}><img src={asset(ingredients[i].file)} alt={ingredients[i].name}/><h3>{ingredients[i].name}</h3><div>{choices.map(n=><button key={n} aria-label={`${ingredients[i].name} ${challenge.d}분의 ${n}컵`} aria-pressed={(i===0?a:b)===n} disabled={disabled||solved} onClick={()=>i===0?setA(n):setB(n)}><Fraction numerator={n} denominator={challenge.d} unit="컵"/></button>)}</div></div>)}</div></>:<div className="special-ingredients special-stock"><div><h3>현재 재고</h3><Fraction numerator={challenge.stock} denominator={challenge.d} unit="컵"/></div><div><h3>목표 재고</h3><Fraction numerator={challenge.target} denominator={challenge.d} unit="컵"/></div><div><h3>얼마를 사용할까요?</h3><div>{challenge.options.map(n=><button key={n} aria-label={`사용량 ${challenge.d}분의 ${n}컵`} aria-pressed={choice===n} disabled={disabled||solved} onClick={()=>setChoice(n)}><Fraction numerator={n} denominator={challenge.d} unit="컵"/></button>)}</div></div></div>}
 <p role="status">{message}</p><button className="orange" disabled={disabled||(challenge.type==='combine'?a===null||b===null:choice===null)} onClick={submit}>{solved?'보너스 받고 영업 계속하기':challenge.type==='combine'?'재료 조합 완성!':'사용량 선택 완료!'}</button></section></div>
}
