import {useEffect,useMemo,useRef,useState} from 'react';
import {days,staff,customers,drinks,ingredients} from './data/gameData';
import {generateOrders,calculateScore} from './game/generator';
import {loadSave,saveData} from './storage';
import type {DayConfig,Mode,Order,PlayerResult,Screen} from './types';
import {FractionValueView as F,Equation} from './components/Fraction';
import {asset,manifest,preload} from './assets';
import {audio} from './services/audio';
import {event,initAnalytics} from './services/analytics';
import {DenominatorSetup,ResultLabel,SpecialOrder,specialChallenge,HelpConceptExamples,useDialogFocus} from './components/ConceptControls';
import {GAME_CONFIG} from './game/config';
const value=(n:number,d:number)=>({whole:Math.floor(n/d),numerator:n%d,denominator:d});
const units=(v:{whole:number;numerator:number;denominator:number})=>v.whole*v.denominator+v.numerator;
const time=(ms:number)=>`${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
const accuracy=(r:PlayerResult)=>r.denominatorAttempts!==undefined?Math.round(18/(18+Math.max(0,r.attempts-r.correct))*100):Math.round(r.correct/Math.max(r.correct,r.attempts)*100);
function compare(a:PlayerResult,b:PlayerResult){for(const diff of [a.score-b.score,accuracy(a)-accuracy(b),b.elapsedMs-a.elapsedMs,a.satisfaction-b.satisfaction])if(diff)return diff>0?1:2;return 0}
const isMultiTouch=()=>typeof navigator!=='undefined'&&(navigator.maxTouchPoints??0)>=2;
export default function CafeApp(){
 const [screen,setScreen]=useState<Screen>('TITLE'),[mode,setMode]=useState<Mode>('1P'),[day,setDay]=useState(1),[player,setPlayer]=useState<1|2>(1),[chars,setChars]=useState<[number,number]>([loadSave().selectedCharacter,1]);
 const [seed,setSeed]=useState(1),[first,setFirst]=useState<PlayerResult|null>(null),[result,setResult]=useState<PlayerResult|null>(null),[save,setSave]=useState(loadSave),[modal,setModal]=useState<'help'|'learn'|null>(null),[settings,setSettings]=useState(false),[showDuoInfo,setShowDuoInfo]=useState(false),[confirmReset,setConfirmReset]=useState<'day'|'all'|null>(null),[showRefCup,setShowRefCup]=useState(false),[revision,refresh]=useState(0);
 useDialogFocus(settings,'.audio-panel',()=>setSettings(false));
 const open=(s:Screen)=>{audio.playSfx('uiTap');setScreen(s)};
 const allCleared=days.every(d=>!!save.records[`day-${d.id}`]);
 const openGrand=()=>{if(!save.masterCelebrated){const next={...save,masterCelebrated:true};setSave(next);saveData(next);event('grand_complete_unlocked')}event('grand_complete_view');open('GRAND_COMPLETE')};
 useEffect(()=>{initAnalytics()},[]);
 useEffect(()=>{audio.setTrack(screen==='RESULT'||screen==='GRAND_COMPLETE'?3:screen==='PLAYING'&&(day>=4||mode==='2P')?2:screen==='PLAYING'?1:0)},[screen,day,mode]);
 useEffect(()=>audio.duck(!!modal||settings),[modal,settings]);
 const enter=(m?:Mode)=>{audio.unlock();event('fraction_cafe_enter');if(m==='2P'){tryTwoPlayer();return}open('MODE_SELECT')};
 // 2인 대결 is one single mode on every device — no PC/전자칠판 branching, no touch-based gating. The only thing
 // that changes per visit is whether the one-time "2인 대결 안내" modal shows first; navigator.maxTouchPoints is
 // never used to decide whether 2P is reachable, only (elsewhere, informationally) to show a small "동시 터치
 // 사용 가능" hint that has no effect on gameplay.
 const tryTwoPlayer=()=>{let seen=false;try{seen=localStorage.getItem('fractionCafe_duoInfoSeen')==='1'}catch{}if(seen)open2P();else setShowDuoInfo(true)};
 const open2P=()=>{setMode('2P');open('MODE_SELECT');event('mode_select',{mode:'2p'})};
 const confirmDuoInfo=()=>{try{localStorage.setItem('fractionCafe_duoInfoSeen','1')}catch{}setShowDuoInfo(false);open2P()};
 const saveRecord=(r:PlayerResult)=>{const k=`day-${day}`,old=save.records[k],next={...save,records:{...save.records,[k]:!old||r.score>old.score?r:old}};setSave(next);saveData(next)};
 // The reference-cup reminder shows on every single start (any DAY, 1P or 2P) — not just once ever — since it's
 // a quick "same cup, every time" reminder, not a one-time tutorial.
 const start=(id=day)=>{setDay(id);setPlayer(1);setFirst(null);setResult(null);setSeed(Date.now()>>>0);setModal(null);open('PLAYING');event('game_start',{mode:mode.toLowerCase(),day:id});try{localStorage.setItem('fractionCafe_lastDay',String(id))}catch{}
  setShowRefCup(true)};
 const closeRefCup=()=>setShowRefCup(false);
 const finish=(r:PlayerResult)=>{event('day_clear',{day,score:r.score,accuracy:accuracy(r)});audio.playSfx('dayClear');setResult(r);saveRecord(r);open('RESULT')};
 const finishBattle=(r1:PlayerResult,r2:PlayerResult)=>{const winner=compare(r1,r2);event('day_clear',{day,score:Math.max(r1.score,r2.score),accuracy:Math.max(accuracy(r1),accuracy(r2))});audio.playSfx('dayClear');setFirst(r1);setResult(r2);saveRecord(winner===2?r2:r1);event('battle_result',{day,winner});open('RESULT')};
 const show=(kind:'help'|'learn')=>{event(kind==='help'?'help_open':'learning_content_open',{day});setModal(kind)};
 const resetDayRecord=()=>{const records={...save.records};delete records[`day-${day}`];const next={...save,records};setSave(next);saveData(next);event('records_reset',{scope:'day',day});setConfirmReset(null)};
 const resetAllRecords=()=>{const next={...save,records:{},masterCelebrated:false};setSave(next);saveData(next);event('records_reset',{scope:'all'});setConfirmReset(null)};
 return <div className="game-shell" onPointerDownCapture={()=>audio.unlock()}><main className={`game-stage state-${screen.toLowerCase()}`}>
 {screen!=='PLAYING'&&<SoundButton className="floating" onClick={()=>setSettings(!settings)}/>}
 {screen==='TITLE'&&<section className="opening"><div className="title-art"><img src={asset(manifest.title)} alt="딱 맞춰! 분수카페 — 학교 축제 교실 카페" fetchPriority="high"/><button className="hotspot enter" aria-label="카페 입장" onClick={()=>enter()}/><button className="hotspot solo" aria-label="1인 플레이" onClick={()=>enter('1P')}/><button className="hotspot duo" aria-label="2인 플레이" onClick={()=>enter('2P')}/><button className="hotspot resume" aria-label="이어하기" onClick={()=>{audio.unlock();try{setDay(Math.min(6,Math.max(1,Number(localStorage.getItem('fractionCafe_lastDay'))||1)))}catch{}open('DAY_SELECT')}}/><button className="hotspot help" aria-label="도움말" onClick={()=>show('help')}/></div><div className="creator">기획·제작: 쓰로인훈쌤 김종훈<small>초등 수업을 위한 무료 교육 콘텐츠</small></div></section>}
 {screen==='MODE_SELECT'&&<StaffSelect mode={mode} chars={chars} onMode={m=>{setMode(m);event('mode_select',{mode:m.toLowerCase()})}} onRequestTwoPlayer={tryTwoPlayer} onPick={(slot,id)=>{const next:[number,number]=[...chars];next[slot]=id;setChars(next);event('staff_select',{player:`${slot+1}p`,staff_id:id});if(slot===0){const data={...save,selectedCharacter:id};setSave(data);saveData(data)}}} onNext={()=>open('DAY_SELECT')} onBack={()=>open('TITLE')}/>}
 {screen==='DAY_SELECT'&&<section className={`menu day-menu ${mode==='2P'?'two-player':''}`}>{mode==='2P'?<><div className="day-portrait p1"><span className="vs-tag p1">1P</span><img src={asset(staff[chars[0]].file)} alt=""/><b>{staff[chars[0]].name}</b></div><div className="day-portrait p2"><span className="vs-tag p2">2P</span><img src={asset(staff[chars[1]].file)} alt=""/><b>{staff[chars[1]].name}</b></div><Sign title="오늘은 어떤 영업에 도전할까요?" subtitle="배우고 싶은 DAY를 골라요"/><p className="two-player-note">2인 동시 대결 · 전자칠판/태블릿 권장</p></>:<><Sign title="오늘은 어떤 영업에 도전할까요?" subtitle="배우고 싶은 DAY를 골라요"/><img className="menu-host" src={asset(staff[chars[0]].file)} alt="카페 직원"/></>}<div className="day-cards">{days.map(d=><button key={d.id} className={`day-card ${day===d.id?'selected':''}`} style={{'--accent':d.accent} as React.CSSProperties} onClick={()=>{setDay(d.id);audio.playSfx('uiTap');event('day_select',{day:d.id})}}><b>DAY {d.id}</b><h2>{d.title}</h2><div className="day-art"><img src={asset(drinks[(d.id-1)%4].file)} alt=""/><span>{d.id<3?'+':'−'}</span><img src={asset(ingredients[d.id-1].file)} alt=""/></div><strong>{d.concept}</strong><small>{save.records[`day-${d.id}`]?`★ 최고 ${save.records[`day-${d.id}`].score}점`:d.short}</small></button>)}</div><nav>{allCleared&&<button className="purple" onClick={()=>{event('master_badge_click');openGrand()}}>🏆 6일 영업 완주</button>}<button onClick={()=>open('MODE_SELECT')}>‹ 뒤로</button><button className="blue" onClick={()=>show('learn')}>학습 내용 보기</button><button className="green" onClick={()=>start()}>영업 시작! ▶</button></nav></section>}
 {screen==='PLAYING'&&(mode==='1P'
 ?<Gameplay key={`${seed}-1`} day={days[day-1]} mode={mode} player={1} staffId={chars[0]} seed={seed} paused={!!modal||settings||showRefCup} onHelp={()=>show('help')} onLearn={()=>show('learn')} onSettings={()=>setSettings(!settings)} onExit={()=>open('DAY_SELECT')} onComplete={finish}/>
 :<BattleArena key={seed} day={days[day-1]} seed={seed} chars={chars} paused={!!modal||settings||showRefCup} onHelp={()=>show('help')} onLearn={()=>show('learn')} onSettings={()=>setSettings(!settings)} onExit={()=>open('DAY_SELECT')} onComplete={finishBattle}/>)}
 {screen==='RESULT'&&result&&<section className="celebration"><div className="confetti" aria-hidden="true">✦ · ✧ · ✦ · ✧ · ✦</div><Sign title={mode==='1P'?`DAY ${day} 완료!`:compare(first!,result)===0?'사이좋게 무승부!':`${compare(first!,result)}P 승리!`} subtitle="오늘의 영업 결과"/><div className="result-layout"><img className="result-host" src={asset(staff[chars[player-1]].file)} alt="축하하는 직원"/>{first&&mode==='2P'&&<div className="result-board"><h2>1P</h2><strong className="score">{first.score.toLocaleString()}점</strong><ResultStats r={first}/></div>}<div className="result-board"><h2>{mode==='2P'?'2P':'오늘의 분수 바리스타'}</h2><div className="stars">{'★'.repeat(result.stars)}{'☆'.repeat(3-result.stars)}</div><strong className="score">{result.score.toLocaleString()}점</strong><ResultStats r={result}/></div></div><nav>{allCleared&&<button className="purple" onClick={openGrand}>🏆 6일 영업 완주 축하 보기!</button>}<button className="orange" onClick={()=>start()}>다시 도전</button><button className="green" onClick={()=>open('DAY_SELECT')}>다음 영업 ▶</button><button className="blue" onClick={()=>open('TITLE')}>메인으로</button></nav></section>}
 {screen==='GRAND_COMPLETE'&&<section className="celebration grand-complete"><div className="confetti" aria-hidden="true">✦ · ✧ · ✦ · ✧ · ✦</div><div className="grand-cast" aria-hidden="true"><img className="gc-char gc-yellow" src={asset(staff[0].file)} alt=""/><img className="gc-char gc-green" src={asset(staff[1].file)} alt=""/><img className="gc-char gc-blue" src={asset(staff[2].file)} alt=""/><img className="gc-char gc-purple" src={asset(staff[3].file)} alt=""/></div><div className="grand-center"><Sign title="🎉 모든 영업 완료!" subtitle="딱 맞춰! 분수카페 대성공!"/><p className="grand-sub">6일 동안 분수카페를 멋지게 운영했어요!</p><dl className="grand-stats"><div><dt>획득한 별</dt><dd>{days.reduce((sum,d)=>sum+(save.records[`day-${d.id}`]?.stars??0),0)} / 18</dd></div><div><dt>평균 정확도</dt><dd>{Math.round(days.reduce((sum,d)=>{const r=save.records[`day-${d.id}`];return sum+(r?accuracy(r):0)},0)/6)}%</dd></div><div><dt>최고 콤보</dt><dd>×{Math.max(...days.map(d=>save.records[`day-${d.id}`]?.bestCombo??0))}</dd></div><div><dt>총 성공 주문</dt><dd>{days.reduce((sum,d)=>sum+(save.records[`day-${d.id}`]?.correct??0),0)}개</dd></div></dl><div className="grand-badges">{days.map(d=><div key={d.id} className="grand-badge"><b>DAY {d.id}</b><span>{d.concept}</span></div>)}</div><h2 className="grand-trophy">🏆 분수카페 마스터!</h2><nav><button className="orange" onClick={()=>open('DAY_SELECT')}>DAY 다시 골라 영업하기</button><button className="blue" onClick={()=>open('DAY_SELECT')}>기록 보기</button><button className="green" onClick={()=>open('TITLE')}>메인으로</button></nav></div></section>}
 {settings&&<aside className="audio-panel" role="dialog" aria-modal="true" aria-label="소리 설정"><h3>카페 소리</h3>{(['bgm','sfx'] as const).map(kind=><button key={kind} aria-pressed={audio[kind==='bgm'?'bgmEnabled':'sfxEnabled']} onClick={()=>{audio.set(kind,!audio[kind==='bgm'?'bgmEnabled':'sfxEnabled']);event(kind+'_toggle',{enabled:Number(audio[kind==='bgm'?'bgmEnabled':'sfxEnabled'])});refresh(revision+1)}}>{kind==='bgm'?'배경음악':'효과음'} <b>{audio[kind==='bgm'?'bgmEnabled':'sfxEnabled']?'ON':'OFF'}</b></button>)}<div className="record-manage"><h3>기록 관리</h3><button className="cream" onClick={()=>setConfirmReset('day')}>DAY {day} 기록 초기화</button><button className="cream danger" onClick={()=>setConfirmReset('all')}>전체 기록 초기화</button></div><CloseButton label="소리 설정 닫기" onClick={()=>setSettings(false)}/></aside>}
 {modal&&<Guide kind={modal} day={day} inGame={screen==='PLAYING'} onClose={()=>setModal(null)} onStart={start}/>}
 {showDuoInfo&&<DuoInfoModal onStart={confirmDuoInfo} onBack={()=>setShowDuoInfo(false)}/>}
 {confirmReset&&<ResetConfirmModal kind={confirmReset} day={day} onConfirm={confirmReset==='day'?resetDayRecord:resetAllRecords} onCancel={()=>setConfirmReset(null)}/>}
 {showRefCup&&<ReferenceCupIntroModal onClose={closeRefCup}/>}
 </main></div>;
}
function Sign({title,subtitle}:{title:string;subtitle:string}){return <header className="wood-sign"><small>{subtitle}</small><h1>{title}</h1></header>}
function SoundGlyph({active}:{active:boolean}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M4 9v6h4l5 4.5V4.5L8 9H4Z" fill="currentColor" stroke="none"/>{active?<><path d="M15.5 8.5a5 5 0 0 1 0 7"/><path d="M18 6a8.5 8.5 0 0 1 0 12"/></>:<path d="M16 9l5 6M21 9l-5 6"/>}</svg>}
function SoundButton({className='',onClick}:{className?:string;onClick:()=>void}){const on=audio.bgmEnabled||audio.sfxEnabled;return <button className={`sound-button ${className}`} aria-label="소리 설정" onClick={onClick}><SoundGlyph active={on}/><i className={`sound-dot ${on?'on':'off'}`}/></button>}
function CloseIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.8" strokeLinecap="round" aria-hidden="true"><path d="M6 6L18 18M18 6L6 18"/></svg>}
function CloseButton({label='닫기',className='',onClick}:{label?:string;className?:string;onClick:()=>void}){return <button className={`modal-close ${className}`} aria-label={label} onClick={onClick}><CloseIcon/></button>}
function VsPreview({chars,compact=false}:{chars:[number,number];compact?:boolean}){return <div className={`vs-preview ${compact?'compact':''}`}><div className="vs-side p1-side"><span className="vs-tag p1">1P</span><img src={asset(staff[chars[0]].file)} alt=""/><b>{staff[chars[0]].name}</b></div><div className="vs-mid">VS</div><div className="vs-side p2-side"><span className="vs-tag p2">2P</span><img src={asset(staff[chars[1]].file)} alt=""/><b>{staff[chars[1]].name}</b></div></div>}
function DuoInfoModal({onStart,onBack}:{onStart:()=>void;onBack:()=>void}){useDialogFocus(true,'.touch-info',onBack);return <div className="guide-shade"><section role="dialog" aria-modal="true" aria-label="2인 대결 안내" className="touch-info"><CloseButton onClick={onBack}/><h2>2인 대결 안내</h2><p>두 플레이어가 같은 주문에 도전해요!<br/>멀티터치가 가능한 전자칠판·터치 디스플레이에서는<br/>두 사람이 동시에 조작할 수 있어요.<br/>마우스나 싱글터치 환경에서는<br/>양쪽 작업대를 번갈아 조작할 수 있어요.</p><nav><button className="cream" onClick={onBack}>돌아가기</button><button className="purple" onClick={onStart}>대결 시작!</button></nav></section></div>}
function ResetConfirmModal({kind,day,onConfirm,onCancel}:{kind:'day'|'all';day:number;onConfirm:()=>void;onCancel:()=>void}){useDialogFocus(true,'.reset-confirm',onCancel);return <div className="guide-shade"><section role="dialog" aria-modal="true" aria-label="기록 초기화 확인" className="reset-confirm"><CloseButton onClick={onCancel}/><h2>정말 초기화할까요?</h2><p>{kind==='day'?`DAY ${day}의 최고점·별·최고 콤보 기록이 초기화됩니다.`:'모든 DAY 기록과 전체 진행도, 6일 완주 기록이 초기화됩니다.'}</p><p className="reset-warn">이 작업은 되돌릴 수 없습니다.</p><nav><button className="cream" onClick={onCancel}>취소</button><button className="orange" onClick={onConfirm}>초기화</button></nav></section></div>}
// Shown once, the first time DAY 1 starts (localStorage-gated) — establishes that every ingredient's fraction is
// measured against ONE shared reference cup, not against each ingredient's own bottle/carton. Reuses the same
// FractionCup visual the player will see during measuring, rather than a new illustration.
function ReferenceCupIntroModal({onClose}:{onClose:()=>void}){useDialogFocus(true,'.ref-cup-intro',onClose);return <div className="guide-shade"><section role="dialog" aria-modal="true" aria-label="분수카페의 기준컵" className="ref-cup-intro"><CloseButton onClick={onClose}/><h2>분수카페의 기준컵</h2><div className="ref-cup-visual"><FractionCup units={4} denominator={4} color="#f3ce60"/></div><p><b>이 컵 가득 = 1컵</b></p><p>레몬도, 우유도, 초코도<br/>모두 이 컵을 기준으로 양을 재요.</p><small>컵을 4등분하면 한 칸은 1/4컵이에요.</small><nav><button className="green" onClick={onClose}>알겠어요!</button></nav></section></div>}
function StaffSelect({mode,chars,onMode,onRequestTwoPlayer,onPick,onNext,onBack}:{mode:Mode;chars:[number,number];onMode:(m:Mode)=>void;onRequestTwoPlayer:()=>void;onPick:(slot:0|1,id:number)=>void;onNext:()=>void;onBack:()=>void}){const [slot,setSlot]=useState<0|1>(0);return <section className="menu staff-menu"><Sign title="오늘은 어떻게 운영할까요?" subtitle="함께할 카페 직원을 선택해요"/><div className="mode-switch"><button className={mode==='1P'?'orange':'cream'} onClick={()=>{onMode('1P');setSlot(0)}}>1인 플레이</button><button className={mode==='2P'?'purple':'cream'} onClick={onRequestTwoPlayer}>2인 대결</button></div>{mode==='2P'&&<><VsPreview chars={chars}/>{isMultiTouch()&&<span className="multitouch-hint" role="status">✓ 동시 터치 사용 가능</span>}<div className="player-tabs"><button aria-pressed={slot===0} onClick={()=>setSlot(0)}>1P · {staff[chars[0]].name}</button><button aria-pressed={slot===1} onClick={()=>setSlot(1)}>2P · {staff[chars[1]].name}</button></div></>}<div className="staff-cards">{staff.map((s,i)=><button key={s.file} aria-pressed={chars[slot]===i} className={chars[slot]===i?'selected':''} onClick={()=>{onPick(slot,i);audio.playSfx('ingredientSelect')}}><span className="selection-mark">{chars[slot]===i?'✓ 선택 완료':`${slot+1}P 직원`}</span><img src={asset(s.file)} alt={s.name}/><h2>{s.name}</h2></button>)}</div><nav><button onClick={onBack}>‹ 뒤로</button>{mode==='2P'&&slot===0?<button className="purple" onClick={()=>setSlot(1)}>2P 직원 선택 →</button>:<button className={mode==='2P'?'purple':'green'} onClick={onNext}>{mode==='2P'?'대결 준비 완료! ▶':'영업 준비 완료! ▶'}</button>}</nav></section>}
type Phase='setup'|'measure'|'combine'|'label'|'serve'|'happy';

// Core per-player game state/logic, shared by the 1P Gameplay screen and each 2P workstation. `holdAt`/
// `onOrderServed` are only used by the battle arena's lockstep sync — 1P never passes them, so this behaves
// byte-for-byte like the original single-player state machine when used standalone.
function usePlayerStation({day,seed,paused,releaseToken,onOrderServed,onComplete}:{day:DayConfig;seed:number;paused:boolean;releaseToken?:number;onOrderServed?:(orderIndex:number,score:number)=>void;onComplete:(r:PlayerResult)=>void}){
 const orders=useMemo(()=>generateOrders(day,seed),[day,seed]),[index,setIndex]=useState(0),o=orders[index],d=o.denominator,addition=day.id<3;
 const [phase,setPhase]=useState<Phase>('setup'),[slot,setSlot]=useState(0),[amounts,setAmounts]=useState([0,0]),[selected,setSelected]=useState<number|null>(null),[opened,setOpened]=useState(false),[removed,setRemoved]=useState(0),[message,setMessage]=useState('주문을 확인해요');
 const [elapsed,setElapsed]=useState(0),[patience,setPatience]=useState(1),[score,setScore]=useState(0),[combo,setCombo]=useState(0),[best,setBest]=useState(0),[errors,setErrors]=useState(0),[satisfaction,setSatisfaction]=useState(0),[happyTime,setHappyTime]=useState(0);
 const [denAttempts,setDenAttempts]=useState(0),[resultAttempts,setResultAttempts]=useState(0),[denTotal,setDenTotal]=useState(0),[resultTotal,setResultTotal]=useState(0),[conceptErrors,setConceptErrors]=useState(0),[specialDone,setSpecialDone]=useState(false);
 const challenge=useMemo(()=>specialChallenge(seed,day.id),[seed,day.id]),specialActive=GAME_CONFIG.specialOrderEnabled&&GAME_CONFIG.maxSpecialOrdersPerShift>0&&index===challenge.index&&!specialDone;
 useEffect(()=>{if(specialActive)event('special_order_start',{day:day.id})},[specialActive]);
 const serving=useRef(false),wrong=useRef(false);const drink=drinks[o.drink],needed=addition?drink.ingredients[slot]:drink.ingredients[1],target=addition?(slot===0?o.left:o.right):o.right,remaining=units(o.left)-removed;
 const mood:'happy'|'impatient'|'normal'=phase==='happy'?'happy':patience<.45?'impatient':'normal';const next=orders[index+1];
 useEffect(()=>{setMessage('주문서를 보고 먼저 컵의 눈금을 설정해요.')},[addition,index]);
 useEffect(()=>{if(next)preload(customers[next.customer-1].normal);preload(customers[o.customer-1].happy);preload(customers[o.customer-1].impatient)},[o,next]);
 useEffect(()=>{if(paused||specialActive)return;const id=setInterval(()=>{if(phase==='happy')setHappyTime(t=>t+100);else{setElapsed(t=>t+100);setPatience(p=>Math.max(0,p-100/o.patienceMs))}},100);return()=>clearInterval(id)},[paused,specialActive,phase,o.patienceMs]);
 // Battle mode (onOrderServed provided) never self-advances on the same tick it reports completion — that would
 // race the parent's lockstep decision (the parent hasn't re-rendered with the fresh "both caught up" state yet).
 // Instead it remembers the releaseToken value at the moment it reported, and only advances once the parent has
 // bumped that token (meaning both sides are confirmed caught up) — a plain number comparison, immune to timing.
 const battleMode=onOrderServed!==undefined;
 const notifiedOrder=useRef(-1),tokenAtNotify=useRef(releaseToken??0);
 const advance=()=>{setIndex(i=>i+1);setPhase('setup');setDenAttempts(0);setResultAttempts(0);setSlot(0);setAmounts([0,0]);setSelected(null);setOpened(false);setRemoved(0);setPatience(1);setHappyTime(0);wrong.current=false;serving.current=false};
 useEffect(()=>{if(happyTime<800||paused)return;
  if(notifiedOrder.current!==index){notifiedOrder.current=index;tokenAtNotify.current=releaseToken??0;onOrderServed?.(index,score)}
  if(index===5){const a=Math.round(18/(18+errors+conceptErrors)*100);onComplete({score,correct:6,attempts:6+errors+conceptErrors,denominatorAttempts:denTotal,resultAttempts:resultTotal,measurementAccuracy:Math.round(6/(6+errors)*100),bestCombo:best,elapsedMs:elapsed,satisfaction:Math.round(satisfaction/6*100),stars:a>=90?3:a>=70?2:1})}
  else if(!battleMode)advance();
  else if((releaseToken??0)>tokenAtNotify.current)advance();
 },[happyTime,paused,releaseToken]);
 const fail=()=>{setErrors(e=>e+1);setCombo(0);wrong.current=true;setMessage('조금 달라요. 재료와 양을 다시 확인해요!');audio.playSfx('wrong');event('order_fail',{day:day.id})};
 const choose=(id:number)=>{if(phase!=='measure'||paused)return;setSelected(id);audio.playSfx('ingredientSelect');setMessage(`${ingredients[id].name} 선택! ${addition?'붓기':'재료 덜기'}로 양을 맞춰요.`)};
 const adjust=(direction:number)=>{if(paused||phase!=='measure')return;if(selected!==needed){setMessage('주문에 적힌 재료를 먼저 선택해 주세요.');return}if(!addition&&day.id>=5&&!opened)return;if(addition)setAmounts(a=>a.map((n,i)=>i===slot?Math.max(0,Math.min(4*d,n+direction)):n));else setRemoved(n=>Math.max(0,Math.min(units(o.left),n+direction)));audio.playSfx('pour')};
 const confirm=()=>{if(paused||phase!=='measure')return;if(selected!==needed||(addition?amounts[slot]:removed)!==units(target)){fail();return}audio.playSfx('correct');if(addition&&slot===0){setSlot(1);setSelected(null);setMessage('딱 맞춰! 두 번째 재료를 골라 주세요.')}else{setPhase('combine');setMessage(addition?'두 재료가 준비됐어요. 합쳐 주세요!':'사용량이 딱 맞아요. 남은 재고를 확인해요!')}};
 const chooseDenominator=(n:number)=>{if(paused||specialActive||phase!=='setup')return;const attempt=denAttempts+1;setDenAttempts(attempt);setDenTotal(t=>t+1);const correct=n===d;event('denominator_select',{day:day.id,selected_denominator:n,correct,attempt});audio.playSfx(correct?'fractionSnap':'wrong');if(correct){setPhase('measure');setMessage(`기준컵 1컵을 ${d}등분했어요! 한 칸은 1/${d}컵이에요.`)}else{setConceptErrors(e=>e+1);setMessage('주문서의 분모를 다시 확인해 봐요!')}};
 const confirmResult=(correct:boolean,attempt:number)=>{if(paused||specialActive||phase!=='label')return;setResultAttempts(attempt);setResultTotal(t=>t+1);event('result_confirm',{day:day.id,correct,attempt});if(correct){setPhase('serve');setMessage('딱 맞춰! 라벨을 붙였어요. 이제 서빙해요!');audio.playSfx('correct');audio.playSfx('fractionSnap')}else{setConceptErrors(e=>e+1);audio.playSfx('wrong')}};
 const combine=()=>{if(paused||specialActive||phase!=='combine')return;setPhase(GAME_CONFIG.resultConfirmationRequired?'label':'serve');audio.playSfx(day.id===2?'fractionSnap':'combine');setMessage(day.id===2?'가득 찬 분수는 온전한 컵으로! 완성량 라벨을 붙여요.':addition?'합친 컵을 보고 완성량 라벨을 붙여요.':'남은 재고를 보고 양을 라벨에 표시해요.')};
 const serve=()=>{if(paused||phase!=='serve'||serving.current)return;serving.current=true;const c=wrong.current?0:combo+1,points=calculateScore(patience,c,!wrong.current)+(denAttempts===1?5:0)+(resultAttempts===1?5:0);setScore(s=>s+points);setCombo(c);setBest(b=>Math.max(b,c));setSatisfaction(s=>s+patience);setPhase('happy');setMessage(`+${points}점! 손님이 활짝 웃어요.`);audio.playSfx(c>1?'combo':'serve');audio.playSfx('customerHappy');event('order_complete',{day:day.id,score:points,accuracy:Math.round(3/(3+Math.max(0,denAttempts-1)+Math.max(0,resultAttempts-1)+(wrong.current?1:0))*100)})};
 const active=phase==='measure'&&!paused&&!specialActive;
 return {seed,index,o,d,addition,phase,slot,amounts,selected,opened,removed,message,elapsed,patience,score,combo,
  denAttempts,challenge,specialActive,drink,needed,target,remaining,mood,next,active,paused,
  choose,adjust,confirm,chooseDenominator,confirmResult,combine,serve,setSpecialDone,setScore,setOpened,setMessage,day};
}
type PlayerStation=ReturnType<typeof usePlayerStation>;

function CustomerOrderLane({o,addition,mood,patience,phase,next}:{o:Order;addition:boolean;mood:'happy'|'impatient'|'normal';patience:number;phase:Phase;next?:Order}){
 return <div className="customer-lane"><div className="active-guest"><div className="guest-bubble">{phase==='happy'?'정말 맛있어요!':patience===0?'괜찮아요, 기다릴게요!':'음료 한 잔 부탁해요!'}</div><div className="guest-crop"><img key={`${o.customer}-${mood}`} src={asset(customers[o.customer-1][mood])} alt={`현재 손님 ${o.customer} ${mood}`}/></div><div className="patience-gauge" aria-label={`손님 기다림 ${Math.round(patience*100)}퍼센트`}><i style={{width:`${patience*100}%`}}/></div></div><OrderTicket order={o} addition={addition}/>{next?<div className="next-guest"><span>다음 손님</span><div className="guest-crop"><img src={asset(customers[next.customer-1].normal)} alt={`다음 손님 ${next.customer}`}/></div><b>{drinks[next.drink].name}</b></div>:<div className="queue-end">마지막 주문!<br/>끝까지 딱 맞춰요</div>}</div>;
}

// The ingredient shelf + measuring/result area + serving tray for ONE player. No customer lane, no order
// ticket, no top HUD in here — those are rendered once by the caller (1P Gameplay, or the shared battle lane).
function PlayerWorkstation({s}:{s:PlayerStation}){
 const {seed,index,o,d,addition,phase,slot,amounts,selected,opened,denAttempts,drink,needed,target,remaining,active,paused,specialActive,day,choose,adjust,confirm,chooseDenominator,confirmResult,combine,serve,setOpened,setMessage}=s;
 return <><IngredientSelector selected={selected} onChoose={choose} disabled={!active}/><section className="mix-station"><h2>{addition?'재료 계량하기':'재고에서 사용하기'}</h2>
 {phase==='setup'?<DenominatorSetup retry={denAttempts>0} d={d} seed={seed+index} disabled={paused||specialActive} onAttempt={chooseDenominator}/>:phase==='label'?<ResultLabel carryParts={day.id===2?o.left.numerator+o.right.numerator:0} d={d} total={addition?units(o.left)+units(o.right):remaining} mixed={day.id===2||day.id>=4} addition={addition} color={ingredients[needed].color} disabled={paused||specialActive} onAttempt={confirmResult}/>:<> {addition?<div className={`two-cups ${phase==='serve'||phase==='happy'?'is-combined':''}`}><div className={slot===0?'active-cup':''}><span>{ingredients[drink.ingredients[0]].name}</span><FractionCup units={amounts[0]} denominator={d} color={ingredients[drink.ingredients[0]].color}/></div><b className="operator">+</b><div className={slot===1?'active-cup':''}><span>{ingredients[drink.ingredients[1]].name}</span><FractionCup units={amounts[1]} denominator={d} color={ingredients[drink.ingredients[1]].color}/></div></div>:<div className="stock-work"><div className={opened?'stock-visual regrouped':'stock-visual'}><span>{opened?'바꾼 재고':'현재 재고'}</span><BottleStock whole={o.left.whole-(opened?1:0)} numerator={o.left.numerator+(opened?d:0)} denominator={d} file={ingredients[needed].file} color={ingredients[needed].color}/>{opened&&<strong className="regroup-note">{day.id===5?`1컵 = ${d}/${d}컵`:`온전한 1컵 = ${d}/${d}컵`}</strong>}</div><b className="operator">→</b><div><span>남은 재고</span><FractionCup units={remaining} denominator={d} color={ingredients[needed].color} hideBadge={phase!=='serve'&&phase!=='happy'}/></div></div>}
 {day.id===2&&(phase==='serve'||phase==='happy')&&<div className="carry-visual"><div><span>분수끼리 모으면</span><BottleStock whole={0} numerator={o.left.numerator+o.right.numerator} denominator={d} file={ingredients[needed].file} color={ingredients[needed].color}/></div><b className="operator">→</b><div className="regrouped"><span>가득 찬 칸은 온전한 1!</span><FractionCup units={units(o.left)+units(o.right)} denominator={d} color={ingredients[needed].color}/></div></div>}
 {(phase==='serve'||phase==='happy')&&<div className="answer-strip"><Equation left={o.left} op={addition?'+':'−'} right={o.right} answer={value(addition?units(o.left)+units(o.right):remaining,d)} unit="컵"/></div>}
 <div className="work-actions">{!addition&&day.id>=5&&!opened?<button className="purple regroup-btn" aria-label={day.id===5?'새 병 열기':'온전한 1 바꾸기'} disabled={!active} onClick={()=>{setOpened(true);audio.playSfx('fractionSnap');setMessage(day.id===5?`기준컵 1컵을 ${d}등분했어요! 1컵 = ${d}/${d}컵`:`온전한 1컵을 ${d}등분해서 ${d}/${d}컵으로 바꿨어요!`)}}><b>{day.id===5?'새 병 열기':'온전한 1 바꾸기'}</b><small>{day.id===5?`(1컵 = ${d}/${d}컵)`:`(온전한 1컵 → ${d}/${d}컵)`}</small></button>:<><HoldButton disabled={!active||selected!==needed} label={addition?'붓기':'재료 덜기'} onStep={()=>adjust(1)}/><HoldButton disabled={!active||selected!==needed} label={addition?'비우기':'되돌리기'} onStep={()=>adjust(-1)} secondary/></>}{phase==='measure'&&<button className="orange" onClick={confirm} disabled={paused}>계량 완료</button>}{phase==='combine'&&<button className="orange" onClick={combine} disabled={paused}>{addition?'합치기':'재고 확인'}</button>}</div></>}</section>
 <aside className="serving-tray"><h2>완성 음료</h2><div className={`drink-zone ${phase==='serve'||phase==='happy'?'ready':''}`}>{phase==='serve'||phase==='happy'?<img src={asset(drink.file)} alt={`완성된 ${drink.name}`}/>:<div className="drink-outline"><span>여기에<br/>음료가 완성돼요</span></div>}</div><b>{drink.name}</b>{(phase==='serve'||phase==='happy')&&(addition?<div className="attached-label" aria-label="확인된 양"><F value={value(units(o.left)+units(o.right),d)} unit="컵"/><span>✦ 딱 맞춰!</span></div>:<div className="attached-label" aria-label="주문 완성"><b>주문 완성!</b><span>✦ 딱 맞춰!</span></div>)}<button className="green" onClick={serve} disabled={phase!=='serve'||paused}>서빙하기</button></aside></>;
}

export function Gameplay({day,mode,player,staffId,seed,paused,onHelp,onLearn,onSettings,onExit,onComplete}:{day:DayConfig;mode:Mode;player:number;staffId:number;seed:number;paused:boolean;onHelp:()=>void;onLearn:()=>void;onSettings:()=>void;onExit:()=>void;onComplete:(r:PlayerResult)=>void}){
 const s=usePlayerStation({day,seed,paused,onComplete});
 const {index,o,addition,mood,patience,phase,next,score,combo,elapsed,message,specialActive,setSpecialDone,setScore}=s;
 return <section className={`playfield ${mode==='2P'?'battle':''}`}><header className="top-hud"><div className="staff-badge"><img src={asset(staff[staffId].file)} alt=""/><div><b>{player}P · DAY {day.id}</b><small>{day.title}</small></div></div><div className="order-progress">주문 <strong>{index+1}</strong> / 6</div><div className="hud-score">★ {score.toLocaleString()}<small>COMBO ×{combo}</small></div><span className="clock">◷ {time(elapsed)}</span><SoundButton onClick={onSettings}/><button aria-label="도움말" onClick={onHelp}>?</button></header>
 {mode==='2P'&&<div className="battle-banner">⚔ 같은 주문 · 같은 손님 · 동시 대결 중!</div>}
 <CustomerOrderLane o={o} addition={addition} mood={mood} patience={patience} phase={phase} next={next}/>
 <div className="cafe-counter"><PlayerWorkstation s={s}/></div>
 <footer className="bottom-status"><button onClick={onExit}>‹ DAY 선택</button><p role="status">{message}</p><button onClick={onLearn}>학습 내용</button></footer>
 {specialActive&&<SpecialOrder seed={seed} day={day.id} disabled={paused} onDone={()=>{setSpecialDone(true);setScore(n=>n+25)}}/>}
 </section>;
}

function SharedBattleHud({chars,s1,s2,onSettings,onHelp}:{chars:[number,number];s1:PlayerStation;s2:PlayerStation;onSettings:()=>void;onHelp:()=>void}){
 return <header className="battle-vs-bar">
  <div className="vs-side p1-side"><span className="vs-tag p1">1P</span><img src={asset(staff[chars[0]].file)} alt=""/><b>{staff[chars[0]].name}</b><span className="vs-score">★ {s1.score.toLocaleString()}<small>COMBO ×{s1.combo}</small></span></div>
  <div className="vs-mid"><b>VS</b><span className="order-progress">주문 {s1.index+1} / 6</span><span className="clock">◷ {time(s1.elapsed)}</span></div>
  <div className="vs-side p2-side"><span className="vs-score">★ {s2.score.toLocaleString()}<small>COMBO ×{s2.combo}</small></span><b>{staff[chars[1]].name}</b><img src={asset(staff[chars[1]].file)} alt=""/><span className="vs-tag p2">2P</span></div>
  <div className="battle-corner-controls"><SoundButton onClick={onSettings}/><button aria-label="도움말" onClick={onHelp}>?</button></div>
 </header>;
}

// SAME ORDER AREA (shared) + P1/P2 WORKSTATIONS (independent) — not two complete Playfields glued together.
function BattleArena({day,seed,chars,paused,onHelp,onLearn,onSettings,onExit,onComplete}:{day:DayConfig;seed:number;chars:[number,number];paused:boolean;onHelp:()=>void;onLearn:()=>void;onSettings:()=>void;onExit:()=>void;onComplete:(r1:PlayerResult,r2:PlayerResult)=>void}){
 const [p1Result,setP1Result]=useState<PlayerResult|null>(null),[p2Result,setP2Result]=useState<PlayerResult|null>(null);
 // Lockstep sync: each side reports the order it just finished (with its running score); once BOTH have
 // reported the SAME order index, briefly show a comparison, then bump releaseToken to let both advance together.
 // releaseToken is a plain counter (not a boolean edge) specifically so two near-simultaneous completions can't
 // race each other into a false "already released" read — each station just compares against the token value it
 // saw at the moment it reported in, immune to render-batching order.
 const [p1At,setP1At]=useState({order:-1,score:0}),[p2At,setP2At]=useState({order:-1,score:0});
 const [releaseToken,setReleaseToken]=useState(0);
 useEffect(()=>{if(p1Result&&p2Result)onComplete(p1Result,p2Result)},[p1Result,p2Result]);
 const bothCaughtUp=p1At.order!==-1&&p1At.order===p2At.order;
 useEffect(()=>{if(!bothCaughtUp)return;const t=setTimeout(()=>{setP1At({order:-1,score:0});setP2At({order:-1,score:0});setReleaseToken(n=>n+1)},1100);return()=>clearTimeout(t)},[bothCaughtUp]);
 // s1/s2 are two fully independent usePlayerStation instances with their own state — nothing here is shared
 // between them beyond the releaseToken handshake above. Their DOM buttons are separate elements the browser
 // dispatches separate pointer/touch events to, so on a real multitouch screen both workstations already respond
 // to simultaneous input with no extra wiring; on a mouse or single-touch screen the same two panes just take
 // turns receiving taps.
 const s1=usePlayerStation({day,seed,paused,releaseToken,onOrderServed:(order,score)=>setP1At({order,score}),onComplete:setP1Result});
 const s2=usePlayerStation({day,seed,paused,releaseToken,onOrderServed:(order,score)=>setP2At({order,score}),onComplete:setP2Result});
 const p1Waiting=p1At.order!==-1,p2Waiting=p2At.order!==-1;
 const waitMsg='✓ 완료! 상대 플레이어를 기다리는 중...';
 return <section className="battle-arena">
  <SharedBattleHud chars={chars} s1={s1} s2={s2} onSettings={onSettings} onHelp={onHelp}/>
  {!(p1Result&&p2Result)&&(()=>{const active=p1Result?s2:s1;return <CustomerOrderLane o={active.o} addition={active.addition} mood={active.mood} patience={active.patience} phase={active.phase} next={active.next}/>})()}
  {bothCaughtUp&&<div className="order-compare-banner" role="status">이번 주문까지 · 1P {p1At.score.toLocaleString()}점 · 2P {p2At.score.toLocaleString()}점</div>}
  <div className="battle-workstations">
   <div className="workstation-pane">{p1Result?<BattleWaiting r={p1Result} label="1P"/>:<PlayerWorkstation s={s1}/>}{s1.specialActive&&!p1Result&&<SpecialOrder seed={seed} day={day.id} disabled={paused} onDone={()=>{s1.setSpecialDone(true);s1.setScore(n=>n+25)}}/>}</div>
   <div className="battle-divider" aria-hidden="true"/>
   <div className="workstation-pane">{p2Result?<BattleWaiting r={p2Result} label="2P"/>:<PlayerWorkstation s={s2}/>}{s2.specialActive&&!p2Result&&<SpecialOrder seed={seed} day={day.id} disabled={paused} onDone={()=>{s2.setSpecialDone(true);s2.setScore(n=>n+25)}}/>}</div>
  </div>
  <footer className="bottom-status"><button onClick={onExit}>‹ DAY 선택</button><p role="status">{p1Waiting||p2Waiting?waitMsg:!p1Result?s1.message:s2.message}</p><button onClick={onLearn}>학습 내용</button></footer>
 </section>;
}
function BattleWaiting({r,label}:{r:PlayerResult;label:string}){return <div className="battle-waiting"><span className="stars">{'★'.repeat(r.stars)}{'☆'.repeat(3-r.stars)}</span><h2>{label} 완료!</h2><strong className="score">{r.score.toLocaleString()}점</strong><p>상대를 기다리는 중...</p></div>}
function OrderTicket({order:o,addition}:{order:Order;addition:boolean}){const drink=drinks[o.drink];return <article className="ticket"><header><img src={asset(drink.file)} alt=""/><div><small>주문을 부탁해요!</small><h2>{drink.name}</h2></div></header><div className="reference-badge">기준컵 1컵 = 1</div>{addition?drink.ingredients.map((id,i)=><div className="ticket-row" key={id}><img src={asset(ingredients[id].file)} alt="" style={{'--ing-scale':ingredients[id].scale} as React.CSSProperties}/><b>{ingredients[id].name}</b><F value={i===0?o.left:o.right} unit="컵"/></div>):<><div className="ticket-row"><img src={asset(ingredients[drink.ingredients[1]].file)} alt="" style={{'--ing-scale':ingredients[drink.ingredients[1]].scale} as React.CSSProperties}/><b>현재 재고</b><F value={o.left} unit="컵"/></div><div className="ticket-row"><span className="use-icon">−</span><b>이번에 사용</b><F value={o.right} unit="컵"/></div></>}</article>}
function IngredientSelector({selected,onChoose,disabled}:{selected:number|null;onChoose:(id:number)=>void;disabled:boolean}){return <aside className="ingredient-shelf"><h2>재료 선택</h2><div>{ingredients.map((ing,i)=><button key={ing.file} disabled={disabled} aria-pressed={selected===i} className={selected===i?'selected':''} onClick={()=>onChoose(i)}><img src={asset(ing.file)} alt="" style={{'--ing-scale':ing.scale} as React.CSSProperties}/><b>{ing.name}</b>{selected===i&&<span className="ingredient-check">✓</span>}</button>)}</div></aside>}
export function FractionCup({units:n,denominator:d,color,blank=false,hideBadge=false}:{units:number;denominator:number;color:string;blank?:boolean;hideBadge?:boolean}){const whole=Math.floor(n/d),part=n%d;return <div className="quantity"><div className="whole-cups" aria-label={`온전한 컵 ${whole}개`}>{Array.from({length:whole},(_,i)=><span key={i} style={{background:color}}>1</span>)}</div><div className="fraction-cup"><div className="cup-liquid" style={{height:`${part/d*100}%`,background:color}}/>{!blank&&Array.from({length:d-1},(_,i)=><i className="cup-division" key={i} style={{bottom:`${(i+1)/d*100}%`,animationDelay:`${i*50}ms`}}/>)}</div>{!hideBadge&&<div className="quantity-badge"><F value={value(n,d)} unit="컵"/></div>}</div>}
function BottleStock({whole,numerator,denominator,file,color}:{whole:number;numerator:number;denominator:number;file:string;color:string}){return <div className="bottle-stock"><div className="bottles" data-count={Math.min(whole,6)}>{Array.from({length:whole},(_,i)=><img src={asset(file)} key={i} alt="온전한 한 병"/>)}</div><div className="fraction-pieces">{Array.from({length:numerator},(_,i)=><i key={i} style={{background:color}}/>)}</div><F value={{whole,numerator,denominator}} unit="컵"/></div>}
function HoldButton({label,onStep,disabled,secondary=false}:{label:string;onStep:()=>void;disabled:boolean;secondary?:boolean}){const timer=useRef<ReturnType<typeof setInterval>|null>(null),cb=useRef(onStep);cb.current=onStep;const stop=()=>{if(timer.current)clearInterval(timer.current);timer.current=null};useEffect(()=>{if(disabled)stop();return stop},[disabled]);return <button className={secondary?'cream':'blue'} disabled={disabled} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);stop();cb.current();timer.current=setInterval(()=>cb.current(),300)}} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop} onClick={e=>{if(e.detail===0)cb.current()}}>{label}</button>}
function ResultStats({r}:{r:PlayerResult}){return <dl className="result-stats">{[['정확도',accuracy(r)+'%'],['최고 콤보','×'+r.bestCombo],['성공 주문',r.correct+'개'],['영업 시간',time(r.elapsedMs)],['손님 만족도',r.satisfaction+'%']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}
function Guide({kind,day,inGame,onClose,onStart}:{kind:'help'|'learn';day:number;inGame:boolean;onClose:()=>void;onStart:(day:number)=>void}){useDialogFocus(true,'.guide',onClose);const [selected,setSelected]=useState(day),[tab,setTab]=useState(0);const example=generateOrders(days[selected-1],25)[0];return <div className="guide-shade"><section role="dialog" aria-modal="true" aria-label={kind==='help'?'카페 이용 안내':'학습 내용 보기'} className="guide"><CloseButton className="close" onClick={onClose}/><h1>{kind==='help'?'카페 이용 안내':'학습 내용 보기'}</h1><div className="guide-tabs">{kind==='help'?['게임 방법','분수 도움','손님 안내'].map((s,i)=><button aria-pressed={tab===i} key={s} onClick={()=>setTab(i)}>{s}</button>):days.map(d=><button key={d.id} aria-pressed={selected===d.id} onClick={()=>setSelected(d.id)}>DAY {d.id}</button>)}</div>{kind==='help'?<div className={`help-cards ${tab===0?'six-steps':''}`}>{(tab===0?['주문 확인','눈금 설정','재료 계량','합치기 · 사용하기','완성량 확인','서빙하기']:tab===1?['똑같이 나누어요','분자는 채운 칸','온전한 한 컵','부족하면 바꿔요']:['주문 중인 손님','다음 손님','기다림 게이지','맛있게 서빙!']).map((title,i)=><article key={title}><span className="step-number">{i+1}</span><h2>{title}</h2>{tab===1?<FractionCup units={[3,2,5,6][i]} denominator={5} color="#f3c84e"/>:<img src={asset(tab===2?customers[i][i===3?'happy':'normal']:i===0?drinks[0].file:i===1?ingredients[1].file:i===2?ingredients[0].file:customers[0].happy)} alt=""/>}<p>{tab===0?['필요한 재료와 양을 봐요.','분모만큼 똑같이 나눠요.','주문 재료를 골라 눈금을 맞춰요.','재료를 합치거나 덜어 내요.','완성량 라벨을 직접 붙여요.','확인된 음료를 손님께 전해요!'][i]:tab===1?['분모는 나눈 칸 수예요.','분자는 채운 칸 수예요.','가득 차면 1이 돼요.','기준컵 1컵을 작은 칸으로 바꿔요.'][i]:['가운데 손님부터 만들어요.','다음 주문은 미리 볼 수 있어요.','늦어도 다시 도전할 수 있어요.','연속 성공하면 콤보가 올라요.'][i]}</p></article>)}</div>:<><h2>DAY {selected} · {days[selected-1].concept}</h2><div className="lesson-physical"><div><h3>현재 양</h3><BottleStock {...example.left} file={ingredients[5].file} color="#bc895e"/></div><div><h3>{selected<3?'합칠 양':'필요한 양'}</h3><BottleStock {...example.right} file={ingredients[5].file} color="#bc895e"/></div>{selected>=5&&<div className="regrouped"><h3>온전한 1 바꾸기</h3><BottleStock whole={example.left.whole-1} numerator={example.left.numerator+example.denominator} denominator={example.denominator} file={ingredients[5].file} color="#bc895e"/></div>}<div><h3>{selected<3?'합친 양':'남은 양'}</h3><FractionCup units={selected<3?units(example.left)+units(example.right):units(example.left)-units(example.right)} denominator={example.denominator} color="#bc895e"/></div></div><Equation left={example.left} op={selected<3?'+':'−'} right={example.right} answer={value(selected<3?units(example.left)+units(example.right):units(example.left)-units(example.right),example.denominator)} unit="컵"/></>}{kind==='help'&&tab===1&&<HelpConceptExamples/>}<button className="green" onClick={()=>inGame||kind==='help'?onClose():onStart(selected)}>{inGame?'영업 계속하기':kind==='help'?'알겠어요!':'이 DAY 시작!'}</button></section></div>}
